- landscape.yml
> kcsp updates 5.13.22

- landscape.yml
> Add Inspur Storage to Cloud Native Storage

- landscape.yml
> add cinq ktp

- landscape.yml
> Move CubeFS to incubating

- landscape.yml
> Update keptn to incubating

- landscape.yml
> Add KCSPs 6.10.22

- landscape.yml
Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
> Aeraki Mesh has become a CNCF sandbox project

- landscape.yml
Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
> change devstats url to aeraki mesh

- landscape.yml
Signed-off-by: Tiexin Guo <guotiexin@gmail.com>
> chore: update devstream to sandbox

- landscape.yml
> Update sigstore record, add repo url

- landscape.yml
https://lists.cncf.io/g/cncf-toc/message/7227
> Update kyverno to incubating

- landscape.yml
> add kcsps 7.14.22

- landscape.yml
> update xopero software

- landscape.yml
> add paladin cloud

- landscape.yml
> add linklogis kcsp

- landscape.yml
> Add best practices for EKS Anywhere

- landscape.yml
Data updates; pre-submission checklist N/A.
> Updating project URLs, adding Distribution project to sandbox

- landscape.yml
Moved CAPE to the category, Continuous Integration & Delivery. 
Signed-off-by: Anuradha Fernando <97432624+anufernando@users.noreply.github.com>
> Moved CAPE to Continuous Integration & Delivery

- landscape.yml
Simple update to the URLs for RX-M in the landscape.
> landscape update rx-m urls

- landscape.yml
- settings.yml
> TW updates 7.26.22

- landscape.yml
Signed-off-by: Alex Olivier <alex@cerbos.dev>
> Add Cerbos

- landscape.yml
> cert updates 8.5.22

- landscape.yml
* [/  Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [/] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [/] Have you picked the single best (existing) category for your project?
* [/] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [/] Have you added your SVG to `hosted_logos` and referenced it there?
* [/] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [/] Does your …
> GEC - fix gec member url

- landscape.yml
> tigera kcsp

- landscape.yml
Triton object storage was acquired by MNX Solutions in April 2022, see https://www.tritondatacenter.com/blog/a-new-chapter-begins-for-triton-and-smartos
Signed-off-by: Nick Wilkens <nick.wilkens@mnxsolutions.com>
> Updated Triton Object Storage

- landscape.yml
> china telecom

- landscape.yml
> update cert k8s

- landscape.yml
https://github.com/cncf/toc/pull/778
> SPIFFE and SPIRE are graduated projects now

- landscape.yml
> update suse kcsp

- landscape.yml
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Adding Flagger and Tetragon as subprojects

- landscape.yml
> aokumo kcsp

- landscape.yml
> update talos linux

- landscape.yml
> Update CC to incubating

- landscape.yml
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Moving Brigade to archived

- landscape.yml
> Update cert manager to incubating

- landscape.yml
> move tsb to service mesh category

- landscape.yml
> Fixed Entigo KTP and KCSP homepage URLs

- landscape.yml
> kcsp updates 9.22.22

- landscape.yml
> Move Istio to CNCF

- landscape.yml
Signed-off-by: cjyabraham <cjyabraham@gmail.com>
> Updating cert manager homepage as requested

- landscape.yml
> Add kubewarden again

- landscape.yml
> Add Prefect to orchestration and scheduling

- landscape.yml
SmartOS was acquired by MNX Solutions in April 2022, see https://www.tritondatacenter.com/blog/a-new-chapter-begins-for-triton-and-smartos
Signed-off-by: Nolan Heimlich [nolan.heimlich@mnxsolutions.com](mailto:nolan.heimlich@mnxsolutions.com)
> Updated SmartOS

- landscape.yml
> Add Kured again

- landscape.yml
> kcsp updates 10.7.22

- landscape.yml
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
> Update OpenFeature to include YouTube, Slack, and Blog Information

- landscape.yml
Kyma is and application runtime, part of SAP Business Technology Platform. It contains the serverless component, but it is much more. PaaS category describes Kyma project much better.
Signed-off-by: Piotr Bochyński <p.bochynski@gmail.com>
> Update Kyma description and move to the right category

- landscape.yml
Signed-off-by: James Hunt <10615884+thetwopct@users.noreply.github.com>
> Updating opencost GitHub repo

- readme_summary.md
Signed-off-by: Catherine Paganini <74001907+CathPag@users.noreply.github.com>
> Some edits to README_SUMMARY.md

- landscape.yml
Signed-off-by: Vihang Mehta <vihang@pixielabs.ai>
> Update summary fields for Pixie

- landscape.yml
Signed-off-by: yanjianbo <yanjianbo@beyondcent.com>
> Change crunchbase of FabEdge to CNCF

- landscape.yml
> Kcsp updates 11.1.22

- landscape.yml
Signed-off-by: Anycodes <liuyu@xmail.tech>
> Update crunchbase of the Serverless Devs

- landscape.yml
> feat: change crunchbase of DevStream to CNCF

- landscape.yml
Adding just in Continuous Optimization category.  Logo should be referenceable now.
Signed-off-by: John Jamie <john.jamie@gmail.com>
> Update landscape with Sedai - 2nd attempt

- landscape.yml
> add deckhouse installer

- landscape.yml
Signed-off-by: zhanghuidinah [dinahzhang0420@gmail.com](dinahzhang0420@gmail.com)
> Change crunchbase of Curve to CNCF

- landscape.yml
Signed-off-by: wangwei <lyzhang1999@users.noreply.github.com>
> Change crunchbase of Nocalhost to CNCF

- landscape.yml
> add helios under tracing

- landscape.yml
Signed-off-by: Pratik Raj <Rajpratik71@gmail.com>
> chore: update details for @keylime project

- landscape.yml
> speedyrails kcsp

- landscape.yml
> fix ktp typos

- landscape.yml
> Test out spec feature in landscape

- landscape.yml
Was asked to fill this in by Richard Collins at Jetstack - this is the [landscape update](https://github.com/cncf/landscape/blob/master/readme_summary.md) for the cert-manager project.
NB: I worked on this with @wallrj who's a fellow cert-manager maintainer!
> Add cert-manager summary fields

- landscape.yml
https://lists.cncf.io/g/cncf-kured-dev
Signed-off-by: Daniel Holbach <daniel@weave.works>
> add kured mailing list

- landscape.yml
Signed-off-by: CNCF-Bot <info@cncf.io>
At the request of @CathPag, this adds to the Summary Page content for the Telepresence project.
> Update Telepresence summary page content in landscape.yml

- landscape.yml
> add shangfu 11.23

- landscape.yml
Signed-off-by: CNCF-Bot <info@cncf.io>
> Add Cilium to the Landscape Project Summary table

- landscape.yml
Signed-off-by: Wojtek Cichoń <wojtek.cichon@protonmail.com>
> Update Akuity and Argo

- landscape.yml
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Flux to graduation

- landscape.yml
> new kcsps 11.30

- landscape.yml
> Telemetryhub url

- landscape.yml
Signed-off-by: beorn7 <beorn@grafana.com>
_Pre-submission checklist removed because this PR only adds the new summary table entries to an already existing entry._
> Add summary table entries for Prometheus

- landscape.yml
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Argo to graduated

- landscape.yml
Signed-off-by: Rein Remmel <rein.remmel@entigo.com>
> Updated Entigo KCSP description and landing page URL.

- landscape.yml
KubeArmor is a CNCF sandbox project. As a project maintainers, recently we received a mail to update the project summary table information. This PR handles that update for `landscape.yml` for KubeArmor's summary information.
Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>
> kubearmor: updated landscape.yml with summary info

- landscape.yml
Updates Porter's website from porter.sh to getporter.org, which is our preferred address to avoid a nation-specific  TLD.
> Update Porter URL

- landscape.yml
> update china telecom

- landscape.yml
> in-toto changes

- landscape.yml
Add repo_url and description to neuvector
Signed-off-by: Rene Luria <rene.luria@infomaniak.com>
> Update neuvector item

- landscape.yml
Signed-off-by: hwdef <hwdefcom@outlook.com>
Ref: https://github.com/cncf/toc/issues/974
> update carina information

- landscape.yml
For https://github.com/cncf/toc/issues/969
> Update merbridge project info

- landscape.yml
This is an update for an Argo PR with a fixed issue on line 4440
Original PR is here - https://github.com/cncf/landscape/pull/2911
> Argo summary

- landscape.yml
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
> Update info of Falco project in landscape.yml

- landscape.yml
> Add sva as ktp 12.20.22

- landscape.yml
**Note:  The previous PR https://github.com/cncf/landscape/pull/2926 added Paralus to the wrong category. Moving it to the correct category.
Signed-off-by: Atulpriya Sharma <sharma.atulpriya@gmail.com>
> Updated Paralus Info

- landscape.yml
Signed-off-by: Chip Zoller <chipzoller@gmail.com>
> Add Kyverno project summary table fields

- landscape.yml
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
> Adding Projects Summary for Harbor

- landscape.yml
Signed-off-by: Omri Gazitt <ogazitt@gmail.com>
> added sandbox status to opcr project

- landscape.yml
Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
> add summary fields for aeraki mesh

- landscape.yml
Signed-off-by: yanjianbo <yanjianbo@beyondcent.com>
Ref: https://github.com/cncf/toc/issues/798
> update FabEdge information

- landscape.yml
Signed-off-by: Qi Xu <tonyxuqqi@outlook.com>
> update landscape.yml for TiKV

- landscape.yml
Signed-off-by: CNCF-Bot <info@cncf.io>
> update landscape.yml for dapr project

- landscape.yml
Signed-off-by: alabulei1 vivian.xiage@gmail.com
Signed-off-by: alabulei1 <vivian.xiage@gmail.com>
> Add WasmEdge's Summary Table

- guide.md
Signed-off-by: HaoTian <t117503445@gmail.com>
> Landscape Guide: Update CI/CD example project status

- landscape.yml
> update landscape.yml for Vitess

- landscape.yml
> update elastisys k8s

- landscape.yml
Signed-off-by: Eric Zhao <sczyh16@gmail.com>
Move [Sentinel](https://github.com/alibaba/Sentinel) from API gateway to service proxy category, which is more appropriate for Sentinel.
> Update: move Sentinel to service proxy category

- landscape.yml
> add archerke

- hosted_logos/pipy.svg
- landscape.yml
Signed-off-by: Ali Naqvi <alinaqvi@flomesh.io>
> Add Pipy proxy to Landscape

- landscape.yml
Signed-off-by: alabulei1 <vivian.xiage@gmail.com>
Signed-off-by: alabulei1 <vivian.xiage@gmail.com>
> Add info for WasmEdge

- landscape.yml
Signed-off-by: chenk <hen.keinan@gmail.com>
> Add trivy-operator into landscape

- landscape.yml
Signed-off-by: qmhu <brillantroad@gmail.com>
> Update gocrane url

- landscape.yml
> daocloud ktp 1.11.23

- landscape.yml
As per the review comments on https://github.com/cncf/landscape/pull/2970#issuecomment-1378976183
Signed-off-by: Faseela K <faseela.k@est.tech>
> Additional updates to Istio Project Summary Table

- landscape.yml
rel https://github.com/cncf/toc/issues/977
Signed-off-by: Alexey Igrychev <alexey.igrychev@flant.com>
> Add sandbox status to werf project

- landscape.yml
intro_url should point to overview video
Signed-off-by: Faseela K <faseela.k@est.tech>
> Update Istio intro URL

- landscape.yml
> update landscape with new armada url

- landscape.yml
> update superorbital ktp

- landscape.yml
> member updates 1.19.23

- landscape.yml
> member updates 1.20.23

- landscape.yml
Signed-off-by: chenk <hen.keinan@gmail.com>
> docs: replace starboard with trivy-operator

- landscape.yml
* [N/A] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* x ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
> Update landscape for Longhorn in 2023

- landscape.yml
Signed-off-by: Doug Davis <dug@microsoft.com>
> More updates for CloudEvents

- landscape.yml
Signed-off-by: Dmitry Shurupov <dmitry.shurupov@palark.com>
The description was outdated; the one I'm proposing is more relevant to how werf is positioned today (based on the project's README file).
> Update werf description in landscape.yml

- landscape.yml
Related to https://github.com/cncf/toc/issues/970
Signed-off-by: Oleg Matskiv <oleg.matskiv@gmail.com>
> Add sandbox status to Devspace project

- landscape.yml
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>
> Add Extra Information for KubeVela

- landscape.yml
Signed-off-by: John Harris <john@johnharris.io>
> Add Kuma updates to landscape

- landscape.yml
This PR adds missing information to the project summary table, as suggested by @CathPag  
> Update Keptn fields

- .github/workflows/verify.yaml
Signed-off-by: Robert Kielty <robert.kielty@cncf.io>
Typo fix on go version.
> fixes type on go-version

- images/cookie-banner.css
- settings.yml
Signed-off-by: cjyabraham <cjyabraham@gmail.com>
> Adds the Osano GDPR cookie banner

- landscape.yml
> Add NHN Cloud as KCSP

- landscape.yml
> add GEC as KCSP 2.1.23

- landscape.yml
> update URL for DoiT

- landscape.yml
> add kcsps 2.8.23

- landscape.yml
> Web landscape web landscape 2023 01 20 t18 40

- landscape.yml
stackstorm's strength and main usage is task orchestration, very similar to dolphin scheduler and prefect
Signed-off-by: Yaakov Gesher <yaakov@gesher.net>
> Moved stackstorm to orchestration category

- landscape.yml
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
**Only editing information for already existing item**
> Updated landscape.yml for Thanos project information

- landscape.yml
https://github.com/cncf/landscape/issues/3037
> add new annual review info

- landscape.yml
> Adding annual sandbox reviews and dates

- landscape.yml
> update k8s conformance 2.13.23

- landscape.yml
> update url whitemist

- landscape.yml
> volcano engine cert k8s 2.15.23

- landscape.yml
> add CubeFS to landscape

- landscape.yml
> Kubevela to incubating

- landscape.yml
> cert k8s 2.24.23

- .github/workflows/linkchecker.yml
- Updates Lychee to `0.11.1`
- Includes hotfixes to reduce flakes due to network instability
Signed-off-by: Taylor Dolezal <onlydole@gmail.com>
> Bump Lychee Action to v1.6.1

- landscape.yml
> update kubevela cii best practices url

- landscape.yml
- settings.yml
> OpenKruise to incubating

- landscape.yml
> Cert K8s updates 3.10.23

- landscape.yml
> kcsps 3.17.23

- landscape.yml
added and updated links for Carvel since becoming Sandbox project
> updated carvel info in landscape

- guide.md
> Fix spelling issue in guide.md

- guide.md
Crossplane and Volcano are incubating projects
> Update guide.md: Fix project status

- landscape.yml
> updating NATS landscape summary items

- landscape.yml
> update alauda ktp

- landscape.yml
/hold for Knative Steering to review
> Updates landscape.yaml with additional Knative information

- landscape.yml
> update clusternet to sandbox

- landscape.yml
> update KubeEdge info

- landscape.yml
Resolves https://github.com/jaegertracing/documentation/issues/622
> Jaeger details for landscape

- landscape.yml
* [] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?
> Added OpenFGA summary_* fields

- landscape.yml
> landscape: add CRI-O extra fields

- landscape.yml
> chore: Update Keptn summary entries

- landscape.yml
> Metal3 project summary

- landscape.yml
Follow up https://github.com/cncf/landscape/pull/3123#discussion_r1160377986 
cc @jmhbnz @mitake @ptabor @serathius @spzala
> Update release rate for etcd

- landscape.yml
> add scaleops to continuous optimization

- landscape.yml
> kcsp update 4.14.23

- landscape.yml
> add repo for paladin

- landscape.yml
Following instructions from https://clomonitor.io/docs/topics/checks/#summary-table 
> update landscape.yml adding summary table fields for k8gb project

- guide.md
> Copy improvement in scheduling and orchestration

- landscape.yml
> remove xenonstack

- landscape.yml
First, thank you for adding Keycloak to the landscape.yml list. Our team would appreciate it if possible to include the changes suggested here, including more details about Keycloak and moving the project to the category 'Security & Compliance', considering that the project goes beyond the scope of key management.
> Update landscape.yml with Keycloak details

- landscape.yml
> Update Konveyor extra summary fields

- landscape.yml
> add chinatelecom cert k8s

- guide.md
> Some punctuation mistakes in the Guide fix 

- landscape.yml
> Remove Gimbal as it's an archived project

- landscape.yml
> add repo to magellano

- landscape.yml
cc @caniszczyk 
More details: https://github.com/cncf/devstats/discussions/7#discussioncomment-5881258
> Update Teller config - DevStats detected inactivity and it was due to move to a new org

- landscape.yml
> add HFTech as KCSP

- landscape.yml
> Update PipeCD to Sandbox

- landscape.yml
> Add squer to kcsp

- landscape.yml
> [backstage] - added some more information about the Backstage project

- landscape.yml
This is related to:
- https://github.com/cncf/toc/pull/1067
- https://github.com/k8up-io/k8up/issues/864
> Add the annual review URL and date for k8up

- landscape.yml
> Update landscape.yml adding bfe 2022 annual review

- landscape.yml
Signed-off-by: antmoveh [shen.ren.love@163.com](shen.ren.love@163.com)
> update carina crunchbase

- landscape.yml
> new kcsps 6.2.23

- landscape.yml
The Ericsson Cloud Container Distribution homepage URL is outdated. This change will replace it with the current one.
> Update Ericsson Cloud Container Distribution homepage

- landscape.yml
Resolves https://github.com/cdk8s-team/cdk8s/issues/1333
> CDK8s Annual review information in landscape (#1)

- landscape.yml
This makes the exports happy to have everything match into CNCF for some sandbox projects that we had pointing to other places.
> Updating Crunchbase to CNCF for sandbox projects

- landscape.yml
> add 6wind CNF

- landscape.yml
> Add annual url to FabEdge

- landscape.yml
> Update landscape.yml for StackRox 

- landscape.yml
> cert k8s updates 6.22.23

- landscape.yml
> Update annual review update for OpenFunction

- landscape.yml
> add sealer annual review information in landscape 

- landscape.yml
> Update HwameiStor project info

- landscape.yml
This might break, but the project has been voted for archive by TOC
> OSM to archive

- landscape.yml
> Update annual review for Serverless Workflow (2022)

- landscape.yml
> s is next to d

- landscape.yml
> cloudgeometry kcsp 7.7.23

- landscape.yml
> add SAP HANA

- landscape.yml
This PR changes the subcategory of Meshery and updates it to "Automation & Configuration" under Provisioning.
> Update Meshery SubCategory

- landscape.yml
> update TKG description

- landscape.yml
> Update Athenz annual review PR and date

- landscape.yml
Update annual review and slack url
> Update Kube-OVN info

- landscape.yml
Add two missing words.
Signed-off-by: Craig Box <craigb@armosec.io>
> Small fix to Istio description

- landscape.yml
> Add KSOC to the Security & Compliance subcategory

- landscape.yml
> KCSP updates 7.21.23

- landscape.yml
> cert k8s updates 7.21.23

- landscape.yml
> Fix ampere's logo filename to pass tests

- .github/workflows/verify.yaml
> move check to checks_requested

- .github/workflows/verify.yaml
> Revert "move check to checks_requested"

- .github/workflows/linkchecker.yml
> Revert "Update linkchecker.yml"

- landscape.yml
The vote/whatnot finished 07/03, but the official acceptance date is 07/25 :)
> Update KubeFlow acceptance date

- landscape.yml
> Update landscape.yml with Kuma annual review

- landscape.yml
This PR updates the annual_review points for the existing Sandbox project KubeArmor. Ref: https://github.com/cncf/toc/pull/1069
> KubeArmor: updated annual review details

- landscape.yml
> Update annual review update for OpenELB

- landscape.yml
> Update annual review for OpenYurt

- landscape.yml
> Update information about Constellation

- landscape.yml
> Update annual review for Virtual Kubelet

- landscape.yml
> update eventmesh link

- landscape.yml
> Annual review update for Confidential Containers

- landscape.yml
> Add ngrok as new member

- landscape.yml
> Fix some security audits dates format

- landscape.yml
Update of PRODYNA company information regarding KCSP cards
> Update PRODYNA (KCSP) website

- landscape.yml
Re-apply fix applied in #3418 that was accidentally reverted in #3424.
> Fix security audit date format

- landscape.yml
> Add TAG storage metadata to Vitess

- cached_logos/kubeservice-stack.svg
- hosted_logos/kubeservice-stack.svg
- landscape.yml
> Add kubeservice stack landscape

- landscape.yml
> Akri annual report

- landscape.yml
> Update information about Samsung Kubernetes Engine (SKE) 

- landscape.yml
- Fix format of a couple of dates
- Remove references to a couple of repositories that no longer exist
> Fix some minor issues in landscape.yml file

- settings.yml
> Update settings.yml to show the Tooling category

- landscape.yml
> kata-containers change url

- landscape.yml
> Fix typo in security audit entry

- landscape.yml
- https://github.com/cncf/artwork/blob/master/examples/incubating.md#opa-logos is not a valid stackoverflow url
- https://www.idemproject.io/general-8 is not a valid repository url
> Remove two invalid urls

- landscape.yml
> Add scheme to some slack urls

- landscape.yml
> Update annual review for Distribution

- landscape.yml
> update microsoft link

- landscape.yml
> Updated VMware Tanzu Healthcare name and description

- settings.yml
https://github.com/cncf/landscape/pull/3478
> Move ngrok: #3478

- landscape.yml
> Add annual review date and url for WasmEdge

- landscape.yml
> kcsp update 9.7.23

- landscape.yml
Adds the Dapr security audit report.
Closes https://github.com/cncf/toc/pull/1164#issuecomment-1710226145
> Add Dapr security audit report

- landscape.yml
> add huawei cnf

- landscape.yml
> cert k8s updates 9.12.23

- hosted_logos/wa-lang.svg
- landscape.yml
> feat: add Wa programming language

- landscape.yml
Also added a short description for GitGuardian in the subcategory
LGTM
> Added GitGuardian in the subcategory Security & Compliance

- landscape.yml
Based off of the recommendation in https://clomonitor.io/projects/cncf/wasm-cloud, I'm adding some additional summary tag information and a project URL for wasmCloud.
> Add extra summary information for wasmcloud

- landscape.yml
> cert-manager: Add last annual review and add slack and youtube link

- hosted_logos/wa-lang.svg
Due to the incorrect display of wa-lang's logo in landscape, it was found that there was a missing SVG attribute during troubleshooting, so the wa-lang logo was updated.
> chore: update wa-lang logo

- landscape.yml
> cert k8s updates 9.21.23

- landscape.yml
> feat: add kcl sandbox project info

- landscape.yml
Copies KEDA entry into "Scheduling & Orchestration" category to address [this issue](https://github.com/cncf/cncf.io/issues/792).
> Make a copy of KEDA into main section of landscape

- landscape.yml
> Archive SMI

- landscape.yml
> Add kcsps 10.2.23

- landscape.yml
> Update Kubeshop projects on landscape.yml

- landscape.yml
> Add annual review date and url for Meshery

- hosted_logos/kcp.svg
- landscape.yml
> Add KCP to landscape

- landscape.yml
> Add ApeCloud as a new database category in landcape.yml

- landscape.yml
> Add dapr to main landscape

- landscape.yml
> Cilium to graduation

- landscape.yml
> landscape: add more fuzzing audits

- landscape.yml
> Add Cilium Graduation Date

- landscape.yml
> add alauda container platform

- landscape.yml
> add kcsps 10.23.23

- landscape.yml
Add Summary and update repository location for project capsule
> docs(capsule): update documentation reference, add summary

- landscape.yml
* [] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
> Move EDB in the correct category (Databases)

- hosted_logos/ly-corp.svg
- landscape.yml
> Member updates 11.2.23

- landscape.yml
> kcsp ktp updates 11.7.23

- landscape.yml
> Update the clomonitor name for WasmEdge

- landscape.yml
adding details about IBM Turbonomic and changing Turbonomic to IBM Turbonomic, now that Turbonomic is part of IBM.
> Update landscape.yml for IBM Turbonomic

- landscape.yml
@jimbugwadia @realshuting @caniszczyk @DavidKorczynski 
> add kyverno security audit report

- landscape.yml
> Add annual review link/date for Submariner

- landscape.yml
> k8s conformance 12.5.23

- landscape.yml
> k8s conformance updates 12.6.23

- landscape.yml
> Karmada incubating

- landscape.yml
> Add Argo security audit

- landscape.yml
> Add Notation security audit

- landscape.yml
> Add Crossplane audits

- landscape.yml
> Add Knative security audit

- landscape.yml
> Karmada to incubation

- landscape.yml
> Fix wrong link to CRI-O security audit

- landscape.yml
This is 404 so it breaks tests, reverting for now
> fix decathlon's crunchbase entry

- landscape.yml
> Fix Submariner's annual review date

- landscape.yml
> Page not found fix for OpenKruise project

- landscape.yml
Between Google domains sale to Squarespace, renewal notice sent out during holidays, etc, zotregistry.io has been parked. We are trying to revive it, however, going forward would move to https://zotregistry.dev
- we have put in better control/process around this. Our sincerest apologies for this disruption
https://github.com/project-zot/zot/issues/2157
* [*] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [*] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [*] Have you picked the single best (existing) category for your project?
* [*] …
> Update zot project website URL

- landscape.yml
> Add Terramate to cicd category

- landscape.yml
> Update Crossplane entry in landscape.yml

- landscape.yml
This PR adds `summary_*` fields to the project description as suggested by CLOMonitor
> chore: update ESO summary table

- landscape.yml
> cert k8s updates 1.23.24

- landscape.yml
> Add graduated date

- landscape.yml
https://github.com/cncf/toc/pull/842
> Strimzi is incubating

- landscape.yml
The date was there, the status was not. Will resolve website issues.
> CloudEvents to graduated

- landscape.yml
The date was there, the status was not.
> Add project status to Strimzi

- landscape.yml
This relates to:
- https://github.com/cncf/toc/pull/1067
- https://github.com/k8up-io/k8up/pull/922
> Update k8up slack channel

- landscape.yml
- Update website
- Update repo_url
- Add blog link
- Add YT link
> confidential-containers: Update project info

- landscape.yml
> Remove broken Crunchbase link

- hosted_logos/merck.svg
- landscape.yml
> Member updates 2.8.24

- landscape.yml
> Updating Numaflow Description

- landscape.yml
> Updated Mia-Platform information

- hosted_logos/stacker.svg
- landscape.yml
https://github.com/cncf/sandbox/issues/73
* [*] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [*] Have you picked the single best (existing) category for your project?
* [*] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [*] Have you added your SVG to `hosted_logos` and referenced it there?
* [*] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [*] Does your project/product name match the text on the logo?
> Update landscape.yml to include stacker

- landscape.yml
> kcsp updates 2.16.24

- landscape.yml
> Fix Inspektor Gadget clomonitor name

- landscape.yml
> kcsp ktp updates 2.28.24

- hosted_logos/kanister.svg
- landscape.yml
Updates to sync with DevStats.
> Updates to match DevStats

- landscape.yml
> add taikun cloudworks to wasm hosted platforms

- landscape.yml
> add taikun tks to kubernetes distribion

- landscape.yml
> add Taikun as a Certified Kubernetes - Installer

- landscape.yml
> update members 3.11.24

- landscape.yml
> update bankware kcsp

- landscape.yml
> kcsp updates 3.14.24

- landscape.yml
* [ x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ x] Have you picked the single best (existing) category for your project?
* [ x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ x] Have you added your SVG to `hosted_logos` and referenced it there?
* [ x] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [ x] Does …
> Added simplyblock to the cloud native storage landscape

- landscape.yml
> [landscape.yml] Fix broken link to Porter

- landscape.yml
> kcsp 4.2.24

- landscape.yml
> Add Cilium LinkedIn page URL

- landscape.yml
https://github.com/cncf/landscape/issues/3814
> Remove stale entry

- landscape.yml
> Update some repositories, crunchbase and homepage urls

- landscape.yml
See https://github.com/cncf/sandbox/issues/49 and https://github.com/cncf/toc/issues/1301
> [WIP] update kubean to be CNCF sandbox

- landscape.yml
> Hi, @pacoxu, could you please create a PR to add the accepted date?
Fix this. https://github.com/cncf/landscape/pull/3836#issuecomment-2061711108
> add accepted date for kubean

- landscape.yml
> move teleport to sec and compliance

- landscape.yml
> update coredge logo

- landscape.yml
> Extra metadata for Radius

- landscape.yml
> Add Unryo to the Landscape

- landscape.yml
> kcsp updates 5.13.24

- landscape.yml
> Add CNCF WasmEdge runtime to the CNCF landscape

- landscape.yml
> update cert k8s 5.16.23

- landscape.yml
> add giant swarm to cert k8s

- landscape.yml
> update volcano engine

- landscape.yml
https://github.com/cncf/toc/pull/728
> Move AritfactHub to Incubating

- landscape.yml
> Add DeepFlow to CNAI Landscape

- landscape.yml
> Update userver framework functionality

- landscape.yml
Update additional summary_* information for Microcks
> Update landscape.yml for Microcks

- landscape.yml
> Add TKS Enterprise Solution and TSK Cloud Services

- landscape.yml
> Update CLOMonitor project name in some projects

- landscape.yml
> Update landscape.yml to include Rig.dev

- landscape.yml
> kcsp updates 6.25.24

- landscape.yml
Moves Curiefense to archived
ref: https://github.com/cncf/toc/issues/1361
> archive curiefense project

- landscape.yml
----
https://github.com/cncf/toc/issues/1369
> feat: add atlantis

- landscape.yml
ref: https://github.com/cncf/toc/issues/1364
> Archive OpenMetrics

- landscape.yml
> kcsp update 7.8.24

- landscape.yml
> update ltimindtree kcsp

- landscape.yml
> Kcsp update 7.10.24

- landscape.yml
https://github.com/anchore/anchore-engine has been archived and is read-only 
See also https://github.com/cncf/landscape/issues/3951 
Doesn't apply as this is removal
> Anchore Engine has been archived

- landscape.yml
> kcsp updates 7.18.24

- landscape.yml
> Update landscape.yml TAG for Kubernetes

- landscape.yml
> member update

- landscape.yml
Hi, I'm one of [the maintainers of the Karmada project](https://github.com/karmada-io/karmada/blob/master/MAINTAINERS.md), this PR updating the summary data as per [the requirements from CLOMonitor](https://clomonitor.io/docs/topics/checks/#summary-table).
> Update summary of Karmada project

- landscape.yml
> update cert k8s 8.14.24

- landscape.yml
> Member updates 8.19.24

- landscape.yml
> cert k8s 8.21.24

- landscape.yml
> update vmware tanzu

- landscape.yml
as https://github.com/cncf/toc/issues/1413, TOC has voted to accept HAMi into the Sandbox.
> update HAMi sandbox information

- landscape.yml
> CNCFMD-1328: Add Okahu AI to observability  category

- landscape.yml
Cleanup to improve https://www.cncf.io/project-metrics/ 
cc @mrbobbytables @caniszczyk
> syntax / data fixes

- landscape.yml
More quick metadata fixes
cc @caniszczyk @cjyabraham
> more metadata fixes

- landscape.yml
> Additional metadata fixes

- landscape.yml
Fixed the typo in logo filename
> Updated monocle logo filename

- landscape.yml
Inline with approved CNCF Sandbox Application
> Update on Project Shipwright

- landscape.yml
Conformance test results: https://github.com/cncf/k8s-conformance/pull/3377
> Add Petasus KaaS to reflect the conformance test results

- landscape.yml
> conformance updates 9.25.24

- landscape.yml
> Last update to Lightrun Logo

- landscape.yml
> move cozystack

- landscape.yml
Thanks to the letters from the community, the kubean team decided to move kubean into the `Automation & Configuration` subcategory.
@taylorwaggoner
> update subcategory for kubean

- landscape.yml
Krustlet is archived: https://github.com/cncf/toc/issues/1385
> Krustlet is archived

- landscape.yml
> add chelsio to cloud native networks

- landscape.yml
Fluid provider changed their webpage from 'http://pasa-bigdata.nju.edu.cn/fluid/index.html' to 'https://fluid-cloudnative.github.io/', this pull request update it.
NA: Not-Apply
* [NA] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [NA] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [NA] Have you picked the single best (existing) category for your project?
* [NA] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [NA] Have you added your SVG to `hosted_logos` and …
> Member 'Fluid' updated

- landscape.yml
> Add Permify to landscape

- landscape.yml
> Fix a typo

- landscape.yml
> Added Middleware to Observability Category 

- landscape.yml
corrects levels and adds appropriate dates :+1:
> landscape audit updates

- landscape.yml
> Add youki to sandbox

- landscape.yml
This was completed in April, cc @kapilt
> Add c7n security audit

- landscape.yml
> Update sandbox projects in landscape.yml

- landscape.yml
> Update release rate KEDA

- landscape.yml
> Update Pomerium's placement in landscape to be more accurate.

- landscape.yml
ref: https://github.com/cncf/toc/issues/1466
> Archive skooner

- hosted_logos/unicloud.svg
- landscape.yml
> Member updates 11.4.24

- landscape.yml
ref: https://github.com/cncf/toc/issues/1478
> Archive FabEdge

- landscape.yml
> Kcsp updates 11.5.24

- landscape.yml
ref: https://github.com/cncf/toc/issues/1479
> Archive curve

- landscape.yml
ref: https://github.com/cncf/toc/pull/1454#issuecomment-2447108229
> Move dapr to graduated

- landscape.yml
ref: https://github.com/cncf/toc/pull/1468#issuecomment-2465963031
vote has gotten enough responses to pass, just bot hasn't updated yet.
> Bump wasmcloud to incubating

- landscape.yml
to avoid confusion between with Trivy, which is the parent project
> remove trivy-operator

- landscape.yml
> kcsp update 11.12.24

- landscape.yml
Hi Reviewers and Approvers,
I am the maintainer of the CNCF Sandbox project, Open Cluster Management.
This PR updates the repo URL to accurately reflect the main repo of our project.
Thank you!
> Update landscape.yml - Open Cluster Management repo URL

- landscape.yml
This just updates repo URL after moved to a separate GitHub org.
> Youki moved to its own GitHub org: youki-dev

- landscape.yml
> Update youki homepage_url

- landscape.yml
> update EMK to cyso

- landscape.yml
This patch adds summary table to containerd project's CNCF landscape entry.
> Add summary table for containerd project

- landscape.yml
* Update name of Oracle Kubernetes Engine (OKE)
* Fix typo in Orka
> Update Oracle Kubernetes Engine (OKE) details

- landscape.yml
> update cisel kcsp

- landscape.yml
ref: https://github.com/cncf/toc/pull/1473#issuecomment-2535226122
> Bump CubeFS to graduated

- landscape.yml
> Update kube-ovn homepage

- landscape.yml
Add summary_ fields for Score as part of the CLOMonitor check: https://clomonitor.io/docs/topics/checks/#summary-table.
> Add summary_ fields for Score

- landscape.yml
Related to cncf/landscape2#777 and cncf/landscape2#780
> Allow associating projects with multiple TAGs

- landscape.yml
> fix izo typo

- landscape.yml
both projects have recently moved from sandbox to incubating.
> Updates OpenYurt and Kubescape

- landscape.yml
> add new kcsp 1.14.25

- landscape.yml
> conformance updates 1.31.25

- landscape.yml
ref: https://github.com/cncf/toc/pull/1522#issuecomment-2647443599
> bump in-toto to graduated

- landscape.yml
> move HAProxy to gold

- landscape.yml
> Add Interlink policy enforcement framework to landscape.yml

- landscape.yml
> Add project field for Cozystack in landscape.yml

- landscape.yml
Ref.: https://github.com/cncf/sandbox/issues/348
> Add Hyperlight container runtime to landscape.yml

- landscape.yml
> gold member 3.14.25

- landscape.yml
> Update k0s entry in landscape.yml with project details and new Crunchbase link

- landscape.yml
> Cert k8s 3.17.25

- landscape.yml
> Gientech cert k8s 3.17.25

- landscape.yml
> pelotech kcsp 3.18.25

- landscape.yml
https://github.com/block/goose/
> Add Goose to landscape

- landscape.yml
> Update Nocalhost project status to archived

- landscape.yml
> Update KubeDL project status to archived in landscape.yml

- landscape.yml
> Update SuperEdge project status to archived in landscape.yml

- landscape.yml
> move CloudNativePG in the Sandbox category

- landscape.yml
I forgot to add social media URLs and other information.
> Integrate CloudNativePG information

- landscape.yml
Updating SAP details in CNCF Landscape
Signed-off-by: evilyeti <krasimir.semerdzhiev@sap.com>
> Updating SAP details in CNCF Landscape

- landscape.yml
> Add composefs project details to CNCF landscape

- landscape.yml
> Add AI metadata field to AI projects

- landscape.yml
This fixes #4313 
I removed only the projects which are not (as far as I can tell from the landscape website) CNCF member projects.
> [Chore]: Remove archived project repos

- landscape.yml
> add kcsps 4.4.25

- landscape.yml
The project moved to using the CNCF Slack instead of Discord
> Update OpenFGA Slack URL

- landscape.yml
(this only updates existing entries, it is not adding any new projects)
> Update CozyStack, Spin & Kaito CNCF Sandbox projects configuration

- landscape.yml
All checked out as I'm updating only for already existing k3s project
Linked to: https://github.com/k3s-io/k3s/issues/12090
> Add k3s summary for the CLOMonitor and Landscape

- landscape.yml
> Add KubeFleet project to landscape with detailed descriptions and links

- landscape.yml
> Edit OpenTofu project with description and update with the CNCF sandbox acception

- landscape.yml
> conformance updates 4.25.25

- landscape.yml
> Member updates 5.1.25

- landscape.yml
> update source allies

- hosted_logos/slc-devopsdays.svg
- landscape.yml
> Member updates 5.16.25

- landscape.yml
> Update landscape.yml to update Drasi description

- landscape.yml
> Update landscape.yml for CubeX

- landscape.yml
Removes Nutanix Objects and replaces with a Kubernetes specific product, Nutanix Data Services for Kubernetes (NDK)
> Replace Nutanix Objects with Nutanix Data Services for Kubernetes

- landscape.yml
> Update LY company url

- landscape.yml
> conformance updates 5.29.25

- landscape.yml
Ref: https://github.com/cncf/sandbox/issues/378
> feat: add urunc as a CRI-compatible runtime for unikernels

- landscape.yml
Updated the URLs with utm_source
> Update landscape.yml - Updated Catalyst by Zoho URLs

- landscape.yml
> K8s conformance updates 7.1.25

- landscape.yml
> Member updates 7.2.25

- landscape.yml
> Update vcluster to vCluster

- landscape.yml
Note: logo was included already for Causely's membership entry, so I am reusing that, similar to how other vendors have it.
> Add Causely in category observability solutions

- landscape.yml
> Remove duplicated project k0s

- landscape.yml
Updating to reflect the most recent archivals. 
This matches https://github.com/cncf/devstats/issues/98
> Update status of recently archived projects

- landscape.yml
This fixes `kagent` join date from `2024-05-22` to `2025-05-22`.
> Fix kagent join date, year should be 2025 not 2024

- landscape.yml
adding k3s linkedin and blsky 
linked to: https://github.com/k3s-io/k3s/issues/12090
> K3s linkedin and blsky

- landscape.yml
> add kagent to CNAI

- landscape.yml
> Update summary details for Meshery

- landscape.yml
> Member updates 8.19.25

- landscape.yml
Metal3 was accepted to incubation at 2025-08-14 at [cncf/toc#1795](https://github.com/cncf/toc/pull/1795).
> move Metal3 to incubating

- landscape.yml
Health Issue: https://github.com/cncf/toc/issues/1584
> Move Keptn to archive

- landscape.yml
> new kcsp 9.4.25

- landscape.yml
> k8s conformance 9.23.25

- landscape.yml
Added social media links for Kubeflow and KServe as well as other metadata.
> Add links for Kubeflow and KServe

- landscape.yml
> Update Cadence Workflow details and repository links
