cncf/landscape

src/components/Footer.js
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> Update terms link

landscape.yml
We're Sensu Inc in Portland, not Sensu in Tokyo, but I'd love to visit them one of these days 😄
=> Correct Crunchbase link for Sensu 🔗

landscape.yml
I believe Infinispan fits the criteria and the mentioned category.  :)
=> Adding Infinispan to Database and Data warehouse category.

landscape.yml
Request to add [Project Flogo](http://flogo.io), an Open Source and Cloud Native Microservice Framework
=> Added Project Flogo

src/index.ejs, webpack.config.dev.js, webpack.config.prod.js
So if it is an error from twitter's widgets.js - we will ignore it.
If that is a different error - we will record a video for next 60 seconds to check what is going on.
Later we can just make a simple list of errors (like all errors initiated from a widgets.js) which we are not going to track.
=> Andrey #353. Ignore twitter errors

tools/generateJson.js
=> Andrey 263 mark fatal errors with a prefix

package.json, tools/addRobots.js
Obviously, you can not see how it will look like on a master branch until you merge
=>  andrey #395 dynamic robots.txt

landscape.yml
=> Add NATS as incubating project

landscape.yml
* [x ] If it is open source, does your project have at least 250 GitHub stars?
* [ x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ x] Are you including an SVG or (less preferably) a large PNG?
* [ x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x ] Does your project/product name match the text on the logo?
* [x ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
=> Update Kong website

package.json, processed_landscape.yml, specs/main.spec.js, src/components/emptyTest.spec.js, src/data.json, tools/ciServer.js
Adding a simple test which opens the generated website in Chrome and then checks if everything keeps working or not.
=> Andrey 286 Adding a basic test

webpack.config.prod.js
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> Change app name

src/components/HomePage.js, src/styles/theme.scss
@dankohn I've made the scrollbar invisible, as I think that standard scrollbar will be ugly there.
=> Add scrollbar to filter bar on short windows #368

landscape.yml
Correcting DaoCloud's url on Crunchbase. Thanks. 😃
=> Correct DaoCloud's URL on Crunchbase

landscape.yml
=> Update SUSE CaaS Platform entry

landscape.yml
=> Update OPA and SPIFFE

src/cncf_members.yml
=> Add new members

src/components/ItemDialogContent.js
=> fix indentation for a latest tweet column. close #484

src/cncf_members.yml
=> Add members

landscape.yml
=> Move Amazon EKS to Certified K8s

landscape.yml
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
=> Add IBM Cloud Container Registry

tools/checkLinks.js, tools/debugCheckLinks.js
Remove false positives.
301/302 are properly displayed
=> improve check links. close #574, #563 and #578

landscape.yml
=> Add Neo4j to landscape.yaml

landscape.yml
Conformance tests in PR https://github.com/cncf/k8s-conformance/pull/213
=> Add open source Gardener

landscape.yml, src/cncf_members.yml
=> Taylorwaggoner new members

landscape.yml, src/cncf_members.yml
=> Taylorwaggoner add new

landscape.yml
=> Add Helm to Incubating

landscape.yml
=> Taylorwaggoner ebaotech

landscape.yml
=> Add DEEP Framework

src/cncf_members.yml
=> Add Datica

landscape.yml
=> Move FusionStage

landscape.yml
=> Added Elastifile to Cloud-Native Storage

package.json, src/data.json, yarn.lock
=> upgrade nodejs to 10.5, close #621

landscape.yml
=> Taylorwaggoner add vke

landscape.yml
=> Add TiKV to Cloud-Native Landscape

landscape.yml
=> Remove Oracle

hosted_logos/k8s-the-easier-way.svg, landscape.yml
=> Taylorwaggoner add k8s tew

landscape.yml
=> Taylorwaggoner add rackspace kcsp

landscape.yml, src/cncf_members.yml
=> Taylorwaggoner member updates

INSTALL.md
=> Fix a typo in INSTALL.md

landscape.yml
* [ X ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ X ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?  Over 1K stars
* [ X ] Have you picked the single best (existing) category for your project?
* [ X ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ X ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ X ] Does your project/product name match the text on the logo?
* [ X ] Have you verified that the Crunchbase data …
=> Add Apache Beam

tools/processSvg.js, tools/testCropFrame.js
This fixes the kube-virt svg image.
=> Do not truncate black pixels. Close #743

landscape.yml
=> Add exoscale to Public cloud category

landscape.yml
update twistlock logo - stacked svg vs. horizontal
=> Update landscape.yml - swap twistlock logo to stacked version

src/data.json, tools/fetchImages.js, tools/generateJson.js
Adding a check that all names are unique. Close #618. Removing an obsolete code which expected that there could be equal names in different categories.
=> ensure that names are unique. Close #618

landscape.yml
=> Add Talend Data Streams

landscape.yml
=> Add MetalK8s Repo

landscape.yml
=> Update NATS logo

landscape.yml
=> Add Twitter URL

landscape.yml
=> Add Azure Stack (ACS) Engine

hosted_logos/percona.svg, landscape.yml
=> Add Percona to databases

landscape.yml
=> Add Robin Hyper-Converged Kubernetes

landscape.yml
Updating the description for CloudOps
=> Update CloudOps Description

src/styles/itemModal.scss
Please check on a real device first. It worked on iPhone7 and on iPhoneX simulator
=> fix landscape layout on iPhone. close #845

landscape.yml
=> Remove Expired Certified Kubernetes

src/components/BigPicture/Elements.js
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> CNCF Sandbox -> Cloud Native Sandbox

landscape.yml
=> Add DeployHub

landscape.yml
Update
singularityware/singularity -> sylabs/singularity
=> Update singularity git repo

src/components/HomePage.js
This works locally when isGoogle is manually set to true.
=> Use a special view when rendering a selected item for the google. close #878

src/components/BigPicture/FullscreenButton.js, src/components/BigPicture/FullscreenButtonContainer.js, src/components/BigPicture/index.js, src/components/CustomAutoSizer.js, src/components/HomePage.js, src/components/HomePageContainer.js, src/reducers/mainReducer.js, src/styles/theme.scss, src/utils/syncToUrl.js
@dankohn , please check
- do we need a fullscreen url support ?
- mobile is not supported, the button is hidden
- in a card mode, the button is hidden too and a fullscreen mode is disabled
=> DO NOT MERGE YET - 801 full screen, close #801

landscape.yml, src/cncf_members.yml
=> Taylorwaggoner exon lv

src/cncf_members.yml
=> Update ENC URL

landscape.yml
=> Add Canonical microk8s

src/components/ItemDialogContent.js
Handling up and down keyboard keys
=> 276 add scroll to dialog

landscape.yml
=> Move Envoy to Graduated

tools/fundingHistoryData.js
Use only those commits which are made by a 'CNCF-Bot' account. Not sure if that was the problem
=> try to fix funding, close #1023

landscape.yml
=> Add Netease

landscape.yml
=> Add ELASTX

landscape.yml
=> Taylorwaggoner remove expired k8s

landscape.yml
=> Move CoreDNS to Graduated

members.yml
=> Remove YugaByte

landscape.yml
=> Rename Stackpoint to NetApp

landscape.yml
=> Add Oteemo as KTP

landscape.yml
=> Add HarmonyCloud as KTP

landscape.yml
=> Update Treasure Data

landscape.yml, members.yml
=> Taylorwaggoner arm

landscape.yml
=> Add Linode CLI

landscape.yml
=> fix links for Presto

landscape.yml
New description for CloudOps (KCSP and KTP).
=> Updated company description for CloudOps

landscape.yml
=> Add puppetlabs-kubernetes

landscape.yml
=> Update ZTE TECS

landscape.yml
=> Add VMware AWS Quick Start

landscape.yml
=> Updated containerd

landscape.yml
=> Update OVH homepage

members.yml
=> Add Darumatic to Members

landscape.yml
=> Add Banzai Cloud PKE

landscape.yml
=> Taylorwaggoner rancher

landscape.yml, members.yml
=> Taylorwaggoner eking

landscape.yml, members.yml
=> Taylorwaggoner kcsps

landscape.yml
=> Add Rancher RKE

landscape.yml
=> Move OPA to Incubating

landscape.yml
From category "Continuous Integration & Delivery" to "Application Definition & Image Build"
=> Move DeployHub to the correct category

landscape.yml
=> Update CRI-O GitHub

landscape.yml, members.yml
=> Add new KCSPs

landscape.yml
=> Update Mirantis KCSP listing text in landscape.yml

landscape.yml
=> Add Grape Up

landscape.yml
=> Add Supergiant to KTP

landscape.yml
=> Update `landscape.yml` for fixing Crunchbase URL of Thundra

landscape.yml
=> Add Mail.Ru

landscape.yml
=> Grape Up - Add description

landscape.yml
=> Add Brobridge to KCSP

landscape.yml
=> Update Alibaba logo

landscape.yml
=> Update CoreHive's name

landscape.yml
=> Update Giant Swarm description

landscape.yml
=> Update Docker logo

landscape.yml
=> Update landscape.yml - Correction of Loodse company description 

landscape.yml
=> Update landscape.yml - Correction Loodse Company description part 2 

landscape.yml
=> Add pomerium

landscape.yml
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> Add Airship

landscape.yml
=> Fix Redirects

landscape.yml
=> Changed the link in the Supergiant KTP entry to supergiant.io/training

landscape.yml
=> Taylorwaggoner baidu

landscape.yml
Adding DANM, a CNI plugin for CNFs.
=> Adding DANM

landscape.yml
=> Update kubeadm description

landscape.yml
=> Update CCP type

landscape.yml
* [X ] Have you picked the single best (existing) category for your project?
* [ X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ X] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ X] Does your project/product name match the text on the logo?
* [X ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
=> Added Scaleway as Public cloud provider

landscape.yml
=> Add Kingsoft

landscape.yml
=> Update Gravitational's logo

landscape.yml
=> fix kubespray homepage url

landscape.yml
=> Add UCloud

landscape.yml
=> Update Azure AKS Engine

landscape.yml
=> Move EasyStack to Distribution

landscape.yml
=> Updated AKS Engine for Azure Stack

landscape.yml
=> Add inovex (KCSP)

settings.yml
Allows to hide a license from a dialog.
=> hide a license

landscape.yml
=> Add KCSP and KTP

members.yml
=> Add Ant Financial

landscape.yml
=> Add KCSPs and KTP

landscape.yml
=> Remove expired Certified K8s

landscape.yml
=> Add Inspur

landscape.yml
=> Add MiaoYun

landscape.yml
=> Add Morpheus

landscape.yml
=> Add Inspur ICKS

landscape.yml
=> Taylorwaggoner d2iq

landscape.yml
=> Update Cloud 66 URL

landscape.yml
=> Add description for Carbon Relay

landscape.yml
=> Taylorwaggoner fix redirects

landscape.yml
=> Update IBM Cloud Kubernetes Service

landscape.yml
=> add repo_url for openshift dedicated

landscape.yml
=> Remove R&D China

landscape.yml
=> Add KTP/KCSP

landscape.yml
=> Update End Users

landscape.yml
Moving Microk8s to the Certified Kubernetes - Distribution subcategory.
=> Update Landscape.yaml - Moving Microk8s

landscape.yml
=> Update Oracle homepage

landscape.yml
=> Add Entigo as KCSP

landscape.yml
=> Taylorwaggoner redirects

landscape.yml
=> update organization and product descriptions of Huawei

landscape.yml
=> Move Alcide to Security & Compliance Section

.npmrc
=> Quiet core-js logging

landscape.yml
=> Update CAIH description

landscape.yml
=> Cybozu Kubernetes Engine

landscape.yml
=> Taylorwaggoner diamanti

landscape.yml
=> Move ahas product from chaos to monitoring

landscape.yml
=> Add Kingsoft Cloud as KCSP

landscape.yml
=> Add Elastisys

landscape.yml
=> Update Red Hat

landscape.yml
=> Add new KCSPs and KTP

landscape.yml
=> Add Cuemby to KTP

landscape.yml
=> Add NEC as KCSP

landscape.yml
=> Add noris network to KCSP

landscape.yml
=> Update Certified K8s

hosted_logos/apache-camel-k.svg, landscape.yml
=> Add Camel K

hosted_logos/inlets.svg, landscape.yml
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
=> Add inlets

landscape.yml
=> Add Tencent to KCSP

landscape.yml
=> Update UCloud logo

settings.yml
Signed-off-by: Jordi Noguera <jordinoguera83+github@gmail.com>
=> Change layout to 16:9

processed_landscape.yml
Signed-off-by: Jordi Noguera <jordinoguera83+github@gmail.com>
Results of diff with changes on `contributors_count`:
```diff
-              contributors_count: 1991
+              contributors_count: 1992
-              contributors_count: 0
+              contributors_count: 29
-              contributors_count: 801
+              contributors_count: 802
-              contributors_count: 0
+              contributors_count: 53
-              contributors_count: 115
+              contributors_count: 114
-              contributors_count: 0
+              contributors_count: 193
-              contributors_count: 314
+              contributors_count: 317
-              contributors_count: 0
+              contributors_count: 304
-              contributors_count: 579
+ …
```
=> Run update to fix contributors count

landscape.yml
=> Move CloudEvents to Incubating

hosted_logos/fossid.svg, landscape.yml
=> Added FOSSID to landscape

landscape.yml
I updated our links to our Kubernetes page
=> Update our links

landscape.yml
=> Update Samsung SDS

landscape.yml
=> Add Conoa as KTP

landscape.yml
=> Add Kazuhm

landscape.yml
=> Add Linode Kubernetes Engine

settings.yml
Some improvements around accessibility by increasing section's contrast. Note there are some additional changes coming in https://github.com/cncf/landscapeapp/pull/472. Especially the background of the landscape will be darker.
=> Improve accessibility

settings.yml
Images must have `alt` attribute for accessibility
=> Add titles to images

settings.yml
Signed-off-by: Jordi Noguera <jordinoguera83+github@gmail.com>
=> Add rel='noopener noreferrer' to outbound links

landscape.yml
=> KCSP / KTP updates

landscape.yml
=> Change HPE to Distribution

landscape.yml
=> Add Siddhi github org url for best practices

landscape.yml
=> Update Upsider homepage

landscape.yml
=> Move Maestro to hosted

hosted_logos/bfe.svg, landscape.yml
=> Update landscape.yml and add bfe

landscape.yml
=> Taylorwaggoner remove expired cert k8s

landscape.yml
=> Update Epsagon to Monitoring

landscape.yml
=> Intellect Design Cert K8s

landscape.yml
=> Add Fullstaq as KCSP

landscape.yml
=> Add Aqua as KCSP

landscape.yml
=> Update products to VMware

landscape.yml
=> Move Architecht

landscape.yml
=> Member Updates

landscape.yml
=> Add Boer Technology to KCSP

landscape.yml
=> Supergiant

landscape.yml
=> Add Puppet as Certified Installer

landscape.yml
=> Add Repo URL to Wind River

landscape.yml
=> Update Nutanix category

landscape.yml
=> Update IBM IKS description

landscape.yml
=> Add new KTPs

landscape.yml
=> Update GKE's description

landscape.yml
=> Add JD Cloud as KCSP

landscape.yml
=> Add twitter link for Gardener

landscape.yml
Appvia requested through member desk
=> Update Appvia description

landscape.yml
=> Update NetApp KCSP Entry

landscape.yml
Nick Chase at Mirantis requested this change
=> Rename Docker EE/CE to Mirantis Docker Enterprise

landscape.yml
=> Add Fury as certified distro

landscape.yml
=> Add ServiceMeme as KCSP

landscape.yml
=> Move Splunk to Gold

landscape.yml
=> Rename Oracle Product

landscape.yml
=> Add Repo URL to Inspur Board

landscape.yml
=> Update information on EMQ Technologies

landscape.yml
=> Transfer KCSP status from Praqma to Eficode

landscape.yml
=> Update WiseCloud description

landscape.yml
=> Add Stakater as KCSP

landscape.yml
=> Add Blue Sentry as KCSP

landscape.yml
=> Add Rafay as KCSP

landscape.yml
=> Update Sysdig logo

landscape.yml
=> Removing expired K8s conformance products

landscape.yml
=> Add StarlingX Twitter URL

landscape.yml
=> Wrong link to homepage of Google Persistent Disk

landscape.yml
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
=> Replace PKS with VMware Tanzu Kubernetes Grid Integrated Edition

landscape.yml
=> Update Certified K8s products

landscape.yml
Member request via member desk
=> Add Logiq to Logging subcategory

landscape.yml
Signed-off-by: jonasrosland <jrosland@vmware.com>
=> Update VMware Tanzu twitter and links

landscape.yml
=> Update Spectro Cloud's Twitter

landscape.yml
=> Add Chronosphere to Monitoring

landscape.yml
=> Update Linode member logo

landscape.yml
Making links more appropriate.
=> Update Flant (KCSP) info in landscape.yml

hosted_logos/mastercard.svg, landscape.yml
=> Taylorwaggoner mastercard

landscape.yml
=> Taylorwaggoner emq

landscape.yml
=> Add OLCNE to Certified K8s

landscape.yml
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Fix typo in State Farm logo

landscape.yml
=> Moving Helm to Graduated

landscape.yml
=> Update Cuemby URL

landscape.yml
=> Update Certified Kubernetes

hosted_logos/lokomotive.svg, landscape.yml
=> Taylorwaggoner certified k8s

landscape.yml
=> Add Rafay as Certified K8s

landscape.yml
=> Fix Stock Tickers

landscape.yml
=> Add Cloudical as KCSP

.github/PULL_REQUEST_TEMPLATE.md
Normal checklist does not apply here.
=> Make time expecation of CNCF-Bot more realistic [skip ci]

landscape.yml
Signed-off-by: Richard Hartmann <richih@richih.org>
=> Move Tanka to "Application Definition & Image Build"

landscape.yml
Add Zettaset to the security section of the trail map.
=> Add Zettaset to the Trail Map

landscape.yml
Added details including website, twtitter & project description for the TiKV project.
=> Update details with regards to the TiKV project

hosted_logos/apioak.svg, landscape.yml
=> Added APIOAK to Landscape.

landscape.yml
=> add flowmill to monitoring

landscape.yml
=> Adding werf to landscape.yml (CI/CD tools)

landscape.yml
This PR updates the Lunar (Supporter), previously Lunar Way information.
=> Update Lunar information

landscape.yml
* [x ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x ] Have you picked the single best (existing) category for your project?
* [x ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x ] Does your logo clearly state the name of the project/product and follow the other logo …
=> Update crunchbase links for Fairwinds

landscape.yml
=> Add HCL as Gold Member

landscape.yml
=> Add Elastisys to KTP

landscape.yml
=> Update Diamanti Cert K8s listing

landscape.yml
* [ *] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [* ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ *] Have you picked the single best (existing) category for your project?
* [* ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ *] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ *] Does your logo clearly state the name of the project/product and follow the other logo …
=> update pandora website

landscape.yml
=> Add Cyber Armor to Security & Compliance

landscape.yml
=> Add LStack as Certified K8s

landscape.yml
=> Certified Kubernetes

landscape.yml
=> new URL for HPE Container Platform + HPE Gold status

landscape.yml
=> Add open Repo URL to Kubermatic Kubernetes Platform

landscape.yml
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
=> fix: fix homepage url for jenkinsX

landscape.yml
=> Updating Harbor to graduated

landscape.yml
Adding to sandbox and changing crunchbase to CNCF
* [] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
=> Updating Keptn, Kudo, LitmusChaos, Kuma, BFE, Crossplane

landscape.yml
=> Adding Contour to incubating

landscape.yml
=> Adding Operator Framework to Incubating

landscape.yml
=> Add Linaro repo

landscape.yml
=> Add WKS as Certified Distro

landscape.yml
=> Add StorPool to Storage

landscape.yml
=> Add Wangsu at KCSP

landscape.yml
=> Nokia Container Services

landscape.yml
=> Adding ChaosMesh to Sandbox

landscape.yml
=> Add cape.sh to CNCF landscape

landscape.yml
The CodeFresh Registry has been shut down effective July 15th.
https://codefresh.io/codefresh-news/deprecation-of-the-codefresh-private-registry/
This PR is to remove them from the CNCF Landscape.
=> Remove CodeFresh Registry

hosted_logos/aqua.svg, landscape.yml
=> New aqua logo

landscape.yml
=> Add iNNOVO as Certified K8s

landscape.yml
=> Update Nokia description

landscape.yml
=> add IBM to Cert K8s

landscape.yml
=> Move Intuit to Gold

landscape.yml
=> Moving Thanos to Incubating

landscape.yml
=> Change Mia-Platform category

landscape.yml
=> Update Mia-Platform description

landscape.yml
=> Update SPD bank

landscape.yml
=> Update Red Kubes

landscape.yml
=> Adding k3s to sandbox

landscape.yml
Two corrections concerning the Serverless Workflow sandbox project.
- the project title should be "Serverless Workflow", not "Serverless Workflow Specification".
- the website is available at https://serverlessworkflow.io (project card currently links to the github specification repo)
Signed-off-by: Manuel Stein <manuel.stein@nokia-bell-labs.com>
=> Corrections to Serverless Workflow

landscape.yml
=> Add Alter Way as KTP

landscape.yml
=> Adding Backstage to Sandbox

landscape.yml
Add Huawei Storage to Cloud Native Storage
=> Add Huawei Storage to landscape

landscape.yml
Demarcate TiKV as a CNCF graduated project - https://www.cncf.io/announcements/2020/09/02/cloud-native-computing-foundation-announces-tikv-graduation/
cc: @dcalvin @WT-liu
=> TiKV Graduation

landscape.yml
Update projects to show Cortex in incubation.
Thanks!
=> Cortex is now in incubation.

landscape.yml
=> New KTP and KCSP

landscape.yml
=> Add Teamsun as Certified Distro

landscape.yml
=> Update to HPE Ezmeral Container Platform

landscape.yml
=> Add Elastisys as Cert K8s

landscape.yml
=> Adding OSM to sandbox

landscape.yml
=> Update Bitnami title and description

landscape.yml, processed_landscape.yml
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>
=> update KubeEdge as incubating project in landscape

landscape.yml
=> Add Gitpod

landscape.yml
Adding twitter account for Cortex Project
=> Added twitter account for Cortex Project

landscape.yml
=> Remove expired conformance

landscape.yml
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Add KubeDB to landscape

landscape.yml
=> Move Epsagon to Tracing

landscape.yml
Keylime was in the wrong area, moving
=> Moving Keylime

landscape.yml
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Add Stash to landscape

landscape.yml
=> Update Cloudbases.io Crunchbase

landscape.yml
=> Add OpenNebula to the CNCF Landscape

README.md, landscape.yml
This is just a fix to an existing entry.
=> Tremor cii

landscape.yml
=> Adding Pravega to Sandbox

landscape.yml
=> Update Sensu's repo

landscape.yml
Minor update to existing project.
=> Update backstage's repo URL

landscape.yml
=> Add Amazon EKS-D as Cert K8s

landscape.yml
=> Add Eficode as KTP

landscape.yml
=> K8s Conformance Updates

landscape.yml
=> Certification updates

landscape.yml
=> Move Epsagon to monitoring

landscape.yml
=> Update Caylent description

landscape.yml
=> Update Buildpacks level

landscape.yml
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Update crunchbase for Carbon Relay

landscape.yml
=> Certified Kubernetes updates

landscape.yml
=> Move OPA to graduated

landscape.yml
=> Corrected home page URL for Dubbo

landscape.yml
=> Update Akana to corrected Crunchbase URL

landscape.yml
=> Add TimescaleDB to the Database category

landscape.yml
https://www.cncf.io/announcements/2020/11/24/cloud-native-computing-foundation-announces-etcd-graduation/
=> etcd should be graduated

landscape.yml
=> Updating Athenz entry

landscape.yml
=> Add join date for latest  10 End Users

landscape.yml
=> Update StormForger to StormForge

landscape.yml
=> Update OpenYurt infos

landscape.yml
=> DigitalOcean

landscape.yml, settings.yml
=> Enlarge Special Category

landscape.yml
=> Add Dosec to security&compliance category

landscape.yml, settings.yml
Rook has moved from Incubating to Graduated ([reference](https://www.cncf.io/announcements/2020/10/07/cloud-native-computing-foundation-announces-rook-graduation/ ))
Also adding new JSON export for CNCF projects, to be used in redevelopment of CNCF.io home page and subsidiary pages
=> Update Rook from Incubating to Graduated

landscape.yml
=> Moving Kube-ovn into the sandbox

landscape.yml
=> Really adding Curiefense to Sandbox

landscape.yml
=> Adding Civo to K8 conformance

landscape.yml
=> Add Civo Membership

landscape.yml
=> Moving Civo to Silver

hosted_logos/fluid.svg, landscape.yml
=> Add Fluid to CNCF landscape

landscape.yml
=> Renaming NIFCloud

landscape.yml
Add Isovalent to the Landscape, and update the URL for the member card.
[Logo already present]
=> Add Isovalent to Cloud Native Network

settings.yml
=> Add CDF Link

landscape.yml
=> Adding OpenKruise to Sandbox

landscape.yml
From a quick glance the following repositories have a license that is
not open source.
https://github.com/stashed/stash | AppsCode
https://github.com/dgraph-io/dgraph | custom named
https://github.com/hazelcast/hazelcast | custom named
https://github.com/kubedb/operator | AppsCode
https://github.com/timescale/timescaledb | custom named
https://github.com/hazelcast/hazelcast-jet | custom named
https://github.com/pachyderm/pachyderm | custom named
https://github.com/vectorizedio/redpanda | BSL
https://github.com/elastic/elasticsearch | SSPL
https://github.com/Graylog2/graylog2-server | SSPL
Fixes: https://github.com/cncf/landscape/issues/2082
=> Correct open-source to false on some projects

landscape.yml
=> Moving New Relic to Platinum

landscape.yml
=> Adding Swisscom as KCSP

landscape.yml
=> Adding KCSP

landscape.yml
=> Adding LIMA as an installer 

landscape.yml
=> Adding StackIT to hosted platforms

landscape.yml
=> add tensor security info to  compliance & security

landscape.yml
Changed the case  (from camel case to upper case only) for the silver member STACKIT
=> Change case of the silver member STACKIT

landscape.yml
=> Add Qingteng to security&compliance category

landscape.yml
=> Switching out Hedvig for Commvault.yml

landscape.yml
=> Added extra data to Kubernetes

landscape.yml
=> Adding KCSPs 6.10.21

landscape.yml
=> Extra data2

landscape.yml
=> Add "extra" metadata to CNCF projects in preparation for automating the sync with cncf.io

landscape.yml
=> Adding KTP to Landscape

netlify.toml
=> Put back functions directory

landscape.yml
=> Adding Cloocus as a KCSP

landscape.yml
=> Adding Joined Dates to End Users

landscape.yml
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR updates "Meshery" which is now a CNCF Sandbox project.
=> Update "Meshery" in the landscape

landscape.yml
=> Fixing RISC-V

landscape.yml
=> Correcting emissary-ingress

landscape.yml
Signed-off-by: guoxudong <guoxudong.dev@gmail.com>
=> update chaosblade to cncf sandbox

landscape.yml
=> Adding Kingsoft to Hosted Platforms

landscape.yml
=> updated Kingsoft Cloud entry

landscape.yml
=> Adding Hosted K8s

landscape.yml
=> Updating GitLab Hubei listing to JiHu GitLab

landscape.yml
=> Correcting K8s category Hosted Platforms

landscape.yml
=> Move linkerd to graduated

hosted_logos/acnodal.svg, landscape.yml
=> Adding Acnodal to landscape

landscape.yml
=> Update twitter account for Deckhouse

landscape.yml
=> Move KEDA to incubation

landscape.yml
=> update leanix description

landscape.yml
Virtasant’s Cloud Optimization solution includes program setup, global cloud expertise, and a proprietary technology platform that offers complete end-to-end automation to manage Cloud FinOps programs and optimize cloud resources.
=> Add Virtasant to landscape Monitoring

landscape.yml
Oracle Linux Cloud Native Environment changed the name to Oracle Cloud Native Environment.
The product page has been updated also.
* [ X ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ NA ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ X ] Have you picked the single best (existing) category for your project?
* [ NA ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [  NA ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ X] Does your logo …
=> Changed the name of Oracle Linux Cloud Native Env

landscape.yml
As per [this issue](https://github.com/cncf/cncf.io/issues/467)
=> Add twitter missing twitter accounts for CNCF projects

landscape.yml
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Change dragonfly repo address.
=> feat: change dragonfly repo address

landscape.yml
=> Move crossplane to incubation

landscape.yml
=> Fix landscape errors

hosted_logos/kratos.svg, landscape.yml
=> feat: add kratos to landscape

landscape.yml
* [* ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [* ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [* ] Have you picked the single best (existing) category for your project?
* [* ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [* ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ *] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ *] Does your …
=> Update landscape.yaml with KubeMQ repo_url

settings.yml
Platinum members export to be used in a revised CNCF join page
=> Adding Platinum members export for JSON feed

landscape.yml
=> conformance expirations 10.05.21

landscape.yml
=> Update flagger to reflex flux sub project

landscape.yml
Signed-off-by: Thomas Graf <thomas@cilium.io>
=> Update Cilium to reflect incubating status

landscape.yml
=> update Cilium crunchbase

landscape.yml
=> certified kubernetes 10.29

landscape.yml
=> Move dapr to incubation

landscape.yml
=> Kcsp updates 11.11

landscape.yml
add project and extra info
cncf/toc#751
=> Update Nocalhost to Sandbox Project

landscape.yml
=> add airlock and yellowbrick

landscape.yml
=> add hypercloud

landscape.yml
=> Add HPE Cert K8s

README.md
=> added: in alphabetical order

landscape.yml
=> kcsp updates 12.15.21

landscape.yml
=> Add Oxeye to Security & Compliance category

landscape.yml
Adds metadata to be included on the searchable KTP page.
=> Add KTP metadata for Polar Squad

landscape.yml
=> Certified K8s updates 1.7.22

landscape.yml
Signed-off-by: ksatchit <karthik@chaosnative.com>
=> Move LitmusChaos to Incubation

landscape.yml
=> Cert K8s updates 1.11.22

landscape.yml
=> Added KTP meta info for use on www.cncf.io

landscape.yml
- `repo_url` is pointing to our general GitHub repo given it is closed source
- Closed source, but Helm chart is [open-source](https://github.com/Azure/api-management-self-hosted-gateway).
- This is our official logo but does not include the name of the service. If this is a problem then I can check with marketin.
=> fix: Improve localization & description for Azure API Management

landscape.yml
=> Membership updates 1.20.22

landscape.yml
=> KCSP updates 1.19.22

landscape.yml
=> Add Sanfor CNAD to Service Proxy

settings.yml
=> update member text

guide.md
Line 895 had a typo - changed "a nd" to "and".
=> Fixed typo in guide.md

landscape.yml
Adding description and removing agent repo URL as this is slightly confusing when trying to our core product offering, the agent is open source but Buildkite isn't 100% open source.
* [x ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x ] Have you picked the single best (existing) category for your project?
* [ x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x ] Have you added your SVG to `hosted_logos` and …
=> Updating Buildkite information in landscape.yml

landscape.yml
https://lists.cncf.io/g/cncf-chaosmesh-maintainers/message/77
=> Move ChaosMesh to Incbuating

landscape.yml, settings.yml
=> Openmetrics - incubating

landscape.yml
=> Remove Daimler

landscape.yml
=> cert k8s updates 2.4.22

landscape.yml
=> Update landscape.yml to include link for Couler

landscape.yml
Signed-off-by: Brad Topol <btopol@us.ibm.com>
=> Updated IBM Cloud description

landscape.yml
=> Add whitemist

landscape.yml
=> KTP KCSP Updates 2.14.22

landscape.yml
=> Update Caddy crunchbase url

landscape.yml
=> Move kubevirt to incubating

landscape.yml
=> add wind river to Cert K8s

landscape.yml
=> update Cilium extras

landscape.yml
=> update knative cncf incubating

landscape.yml
=> wind river 3.2.22

landscape.yml
=> update knative description and crunchbase url

landscape.yml
=> update fujitsu cert K8s

landscape.yml
=> KCSP KTP updates

landscape.yml
=> Move in-toto to incubating

landscape.yml
=> Update Fannie Mae

landscape.yml
=> Updated KICS

landscape.yml
=> add aks engine cert k8s

landscape.yml
=> cert updates 3.18.22

landscape.yml
=> move Volcano to incubating

landscape.yml
Signed-off-by: chenk <hen.keinan@gmail.com>
=> update starboard repo url

landscape.yml
=> Update Flant description

.github/PULL_REQUEST_TEMPLATE.md
It's 30m, not 15m, to build the preview.
=> More realistic website build time

landscape.yml
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Add `mailing_list_url` and `slack_url` to dragonfly landscape.
- Change dragonfly's `homepage_url`.
=> Add mailing_list_url and slack_url to dragonfly landscape

landscape.yml
=> Add Spacelift

landscape.yml
Signed-off-by: Jeffrey Sica <jeef111x@gmail.com>
=> Update cubefs website

landscape.yml
=> add taichu to cert k8s

landscape.yml
=> Add CodeZero to landscape's Application Definition

hosted_logos/confidential-containers.svg, landscape.yml
Completing Task from Sandbox Project onboarding for Confidential Containers -> https://github.com/cncf/toc/issues/799
Signed-off-by: James Magowan <magowan@uk.ibm.com>
=> Adding CNCF sandbox project Confidential Containers to landscape

hosted_logos/pinniped.svg, landscape.yml
=> Add Pinniped to landscape

landscape.yml
=> Update homepage URL for CloudCasa by Catalogic

landscape.yml
=> conformance updates 4.27.22

landscape.yml
See https://github.com/cncf/toc/issues/829
=> add sandbox label to OpenFunction

landscape.yml
=> kcsp updates 4.29.22

landscape.yml
=> Fixed the Argo project slack link

landscape.yml
=> Fix envoy slack url

landscape.yml
=> Update landscape.yml to include Promscale
