landscape.yml
OpenStack != nova - nova is only one component. While the
openstack/openstack repo in github isn't really the exact story either,
it's more correct than the openstack/nova repo.
=> Update repo_url for openstack

src/types/fields.js
The problem was related to the way how we represent selection in the tree.
Usually both parent and children are selected, but when we want to make header links, we set only a child selected. When there are more than 1 child, this is a correct behaviour, but with only one child, we would have to get a parent selected too.
=> Andrey 404 handle an edge case

landscape.yml
Forgot to add repo_url of AppScale in previous pull request (AppScale is open source). Sorry about this oversight.
=> Update repo_url AppScale

landscape.yml
Currently the link is pointing to Couchbase Lite.   I've changed it to point to our main repo for the core database.  Alternative, we could have this link point to https://github.com/couchbase, though I'm not sure if you need specific repos rather than orgs here.
=> Change Couchbase repo to main repo

landscape.yml
* [X ] Are you only including a `repo_url` if your project is 100% open source?
* [X ] Have you picked the single best category for your project?
* [ X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [X ] Are you including an SVG or (less preferably) a large PNG?
* [X ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ X] Does your project/product name match the text on the logo?
* [X ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [X ] 2 minutes after opening the pull request, the CNCF-Bot …
=> Add CyberArk Conjur to Key Management section

landscape.yml
The Vitess repo has moved to a new GitHub org.
=> Update Vitess repo URL.

landscape.yml
Gravitational has renamed Telekube to Gravity and open sourced the code.
=> Rename Telekube to Gravity and include github repo

landscape.yml
kitsune is a programming language that enables any developers to build full stack websites, on serverless architecture on any cloud. Serverless website developed with kitsune are cloud agnostic.
LGTM
=> Adding kitsune to serverless landscape

landscape.yml
Moving gloo to the API Gateway category. It's a better fit.
=> Change Gloo project category

landscape.yml
https://github.com/vmware-archive/hatchway
- item:
name: Hatchway
description: >-
Project Hatchway address this gap in vSphere environments by offering storage infrastructure choices for container environments, from
hyper-converged infrastructure (HCI) powered by VMware vSAN™ to traditional SAN and NAS storage.
homepage_url: 'https://vmware.github.io/hatchway/'
logo: hatchway.svg
crunchbase: 'https://www.crunchbase.com/organization/vmware'
=> Hatchway is abandoned by vmware

landscape.yml
moving Capsule8 from "member" to the "security" category
=> category change for Capsule8

landscape.yml
New URL: https://backstage.io/img/backstage-logo-cncf.svg
=> Update logo URL for Backstage

landscape.yml
NKS is no longer available so the url for NetApp (KCSP) is no longer valid. Updated to point to a proper url.
https://www.storagereview.com/news/netapp-kubernetes-service-nks-come-to-an-end
=> Update NetApp (KCSP) url

landscape.yml
I'm hoping this will fix the detection of our license so it displays as open-source.  I also realized that the twitter entry was defaulting the the CNCF so I'm editing it to use Porter's twitter handle.
**Update: It worked!**  🎉 
This is a follow-up to https://github.com/cncf/landscape/pull/1857 check checked all of these boxes. I'm updating the existing entry.
=> Add repo_url to Porter's entry

README.md
Hi @caniszczyk! 👋 I noticed https://github.com/cncf/landscape/issues/1986 and couldn't resist fixing it. 😇
I didn't find a way to replicate what Netlify does to render the website, so currently this just adds a Gitpod badge that directly opens the `landscape.yml` file in Gitpod:
[![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod)](https://gitpod.io/#https://github.com/cncf/landscape/blob/master/landscape.yml) ↴
From there, new contributors can easily:
- Edit `landscape.yml`
- Upload a new logo
- Create a commit / fork the repo / send a PR
🎉
But, Gitpod could be even more useful here. For example, it could automatically render the resulting website in a Preview (or show any build errors in the console). Are there any useful commands that Gitpod …
=> Add Gitpod badge to README (one-click dev setup)

landscape.yml
Original repo link went to our website repo, which points to all the tool suite but the dev stats listed on the landscape were incorrect, i.e. HTML based. Pointing now directly to one of the tool suite's repos, ytt, for clearer details.
Signed-off-by: Nanci Lancaster <nancil@vmware.com>
* [X Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
=> updated Carvel repo link to point to most relevant project stats

landscape.yml
Move Netflix Zuul from "Service Mesh" to "Service proxy" category.
It's more comparable to Envoy than to Istio, for example.
=> Update Netflix Zuul

landscape.yml
=> fix STACKIT hosted kubernetes product name

.github/PULL_REQUEST_TEMPLATE.md
=> Removes URL option for SVG

landscape.yml
InfraCloud is maintaining the Fission project and Platform9 is not active anymore. Project maintainers would like update the reference in landscape to reflect that.
=> Changing Fission's reference to InfraCloud

landscape.yml
As per https://www.cncf.io/announcements/2021/07/28/cloud-native-computing-foundation-announces-grafana-labs-upgrades-membership-to-platinum/
=> Move Grafana Labs from Silver to Platinum

landscape.yml
This is the first addition of metadata for KTPs as per [this issue](https://github.com/cncf/cncf.io/issues/487).
=> Add KTP metadata for Oteemo

landscape.yml
Homepage link of OpenYurt(github.com/openyurtio/openyurt) have changed as following:
https://openyurt.io/en-us --> https://openyurt.io
https://github.com/cncf/cncf.io/issues/501
=> Update homepage url for OpenYurt

landscape.yml
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>
Last week we submitted wasmCloud to the landscape with our primary runtime repository. We've since made a choice to link to `wasmCloud/wasmCloud` instead as it can serve as a better landing page for the project as a whole.
=> Updated wasmCloud repository

landscape.yml
This adds metadata for several KTPs to the landscape database so that they can be pulled in and queried on the cncf site here: https://www.cncf.io/certification/kubernetes-training-partners/
=> Add KTP metadata to landscape

guide.md
Correcting the Guide's statement that there are ONLY two CNCF projects in the Continuous Integration and Delivery space.  I've added text listing the two incubating and three sandbox projects for tooling, and a mention for the OpenGitOps project which is working on a vendor-neutral definition of GitOps.
Fixes #2399 
=> Correct the Guide's CI/CD section mention of only 2 CNCF projects

landscape.yml
Inlets is now commercial software available on a subscription basis.
Everything else remains the same, other than the repo URL.
=> Updating the inlets repo link

landscape.yml
Updated Could Native storage landscape to include latest homepage links for Apollo 
open-source configuration management system.
=> Update landscape.yml to include link for Apollo configuration management system

landscape.yml
Fix capitalization of "CloudCasa" in landscape member entry.
=> Fix capitalization of CloudCasa entry

landscape.yml
=> refactor: adding Keploy.io Github URL because now it's open-source

landscape.yml
wasmCloud was listed twice, once under “Scheduling & Orchestration” and the second time under “Installable Platform” and so shows up twice [here](https://landscape.cncf.io/card-mode?grouping=no&project=hosted). I've removed the instance under "Installable Platform" as discussed with @caniszczyk .
=> Removing the duplicate entry for wasmCloud

landscape.yml
Kubecost is currently a member company but their product is not on the
landscape. This adds them to the continuous optimisation subcategory as
they are in a similar space to infracost/cast.ai
=> Add kubecost to continuous optimisation subcategory

landscape.yml
An example for a `wasmCloud`
You can see that it is in both categories
=> put wasm in 2 categories

Dockerfile, Makefile, README.md, server.js
Some quick improvements so folks don't need to always have Node.js installed locally to test changes to the landscape. Added a Dockerfile, a Makefile (because Make runs the world), and updated the Readme with the new info.
Also if you run this locally, trying to CTRL+C/sigint didn't work. And I took that personally (and fixed it.) :)
=> Minor developer experience improvements (docker, makefile, ctrl+c support)

landscape.yml
In preparing to automate the [Contribute site project listings](https://contribute.cncf.io/contributors/projects/) and use landscape as the single source of truth, here I fill in the missing values in landscape from the current Contribute site.
=> Updated chat metadata from Contribute site projects listing

landscape.yml
I made a mistake adding kube-green, it has less than 300 stars
=> remove kube-green, less than 300 stars

landscape.yml
This PR adds [SpiceDB](https://github.com/authzed/spicedb) to the landscape.
SpiceDB is a database that's used by various cloud native organizations and has direct integrations with CNCF projects like Kubernetes, Prometheus, OpenTelemetry, gRPC, OPA, Envoy, and I'm sure some others that I'm missing.
As SpiceDB is currently getting a logo designed, I've reused the existing authzed logo as a placeholder in the meantime. I hope this is okay.
=> landscape: add SpiceDB

landscape.yml
This PR updates the slack URL for the Karmada project which official slack has been moved to CNCF during the donation process(see https://github.com/cncf/toc/issues/721#issuecomment-974302115).
=> Update Karmada slack URL

landscape.yml
In prep for creating [a chart of CNCF projects over time](https://github.com/cncf/cncf.io/issues/524), I've added maturation dates as per [the Devstats records](https://github.com/cncf/devstats/blob/master/projects.yaml). When there was a discrepancy between existing dates, I favored the Devstats date. Note that Devstats needs updating in several cases where projects were being listed as being in "Sandbox" when they are listed as "Incubating" in landscape (cc @lukaszgryglicki). There were also other questions that came up:
- when did Cloud Custodian go incubating?
- what date was Brigade archived?
- what date did in-toto go to incubating?
- when did Volcano go to incubating?
- when did Contour go to incubating?
- when did Operator Framework go to incubating?
- when did Chaos Mesh go to …
=> Updated maturation dates as per DevStats

landscape.yml
We moved from freenode to libera.chat a while ago.
Omitting the re-submission checklist because it's just a change of one field.
=> Update slack_url for Prometheus

landscape.yml
Working towards: https://github.com/external-secrets/external-secrets/issues/1395
This PR fixes the devstats URL of external secrets operator.
URL source from this issue here: https://github.com/cncf/toc/issues/882#issuecomment-1202324717
=> fix: external-secrets devstats url

.github/workflows/verify.yaml, cmd/main.go, cmd/verify/verify.go, go.mod, go.sum, pkg/types/types.go, pkg/verify/verify.go
It was a rainy day in Tokyo and I watched sumo while doing this. <3 
- Stubs out a go struct schema for `landscape.yml`
- Creates a golang tooling framework to add functionality to (for future automation)
- Includes a `verify` subcommand which (by default) looks for `landscape.yml` and attempts to verify it against the go struct
- Adds a GitHub action which runs verify on every PR against main
cc @amye @RobertKielty
=> Initial creation of go utils for cncf/landscape

.github/workflows/verify.yaml
Updates the verify GitHub Action on this repo adding a check_suite trigger and also pins the version of go used to run the check to ^1.19.5 when running the go program that checks the correctness of the landscape.yml file.
Post merge this we should then see a verfy step in PRs that checks the landscape.yml file 
cc @jeefy
=> adds check_suite trigger, pins go version

landscape.yml
Fix Seatunnal to Seatunnel.
Signed-off-by: Joris Roovers <joris.roovers@gmail.com>
=> Fix Seatunnel typo

landscape.yml
deckhouse is the only project with www.github.com in hostname . all else are using the proper github.com urls. hence updating it
=> remove inconsistent subdomain for repo url

landscape.yml
The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. 
This pull request proposes an update for project summary table fields for etcd. This will help further inform the community about etcd and its use cases.
Relates to https://github.com/etcd-io/website/issues/658
Leaving this in draft until etcd maintainers have finished reviewing.
cc @ahrtr , @ptabor , @serathius, @spzala
=> Added summary table fields for etcd

landscape.yml
ref https://github.com/cncf/tag-contributor-strategy/pull/429
not sure why it links to an old DaoCloud twitter account which is not maintained.
=> update DaoCloud twitter account

landscape.yml
I've just realized after the merge that we added Direktiv to the wrong category by mistake, sorry for that.
This moves our entry to the correct category. No other changes.
=> Fix category for Direktiv landscape entry

landscape.yml
as suggested by CLOMonitor people https://github.com/kube-rs/kube/issues/1219#issuecomment-1611660030
also killed the twitter link which has been defunct since elon.
=> Update annual review urls in landscape.yml for kube-rs

landscape.yml
The twitter account was bound to the MetalLB original maintainer, who is not handling metallb any more.
=> Remove the twitter account from metallb

landscape.yml
- https://github.com/devspace-sh/devspace-cloud - does not exist.
- https://github.com/devspace-cloud/devspace-cloud - is the new repo.
cc @caniszczyk @castrojo @AndreyKozlov1984
=> Update devspace repo (they moved to a different org)

landscape.yml
This uses the github URLs for the TAG's tags in the metadata.
=> use github urls for TAG tags

landscape.yml
This PR just categorizes wasmCloud as a Wasm orchestration project which is a primary goal of the project. Please let me know if there's another piece of the landscape that I should modify!
=> Categorize wasmCloud as Wasm orchestration

landscape.yml
The Crunchbase url was wrong. CasperLabs develop the Casper-node software but it's controlled by the non-profit association.
=> [WASM] Change Casper Crunchbase URL

hosted_logos/wa-lang.svg
*Fix a problem in logo in wa-lang. In local debug, we found that when executing the build script, the `fill="none"` attribute in the original svg is removed by default, which causes the logo to display incorrectly. After changing to `fill="LightSeaGreen"` (LightSeaGreen is the background color of the logo), the logo is displayed correctly. So fix the fill color of fill in svg so that wa-lang's logo can be displayed correctly.*
=> fix: missing fill attribute of svg in wa logo

.github/workflows/validate.yml
We've released a new version of the landscape2-validate-action that adds support for validating `settings` and `guide` files, in addition to `data` files (i.e. *landscape.yml*). The action parameters have changed a bit, hence the new version.
=> Bump landscape validate action to v2

landscape.yml
This is a quick PR to move Flipt from CD to the new Feature Flags category.
=> Move Flipt from CD to Feature Flags

landscape.yml
=> Fix Artifact Hub dev_stats url

landscape.yml
Since DevSpace is part of CNCF it has moved to https://github.com/devspace-sh/devspace
=> Fix DevSpace github link

landscape.yml
This addresses #3641 by fixing broken links in landscape.yml from [this report](https://docs.google.com/spreadsheets/d/1ST806KAE9Cj9fe2PJ0-h0ciBkDdUd0khwmJrhSxva2g/edit#gid=1105913198). It's important to fix these as they show up on the landscape site, cncf.io and all other downstream sites that consume landscape.yml. Broken links can contribute to lowering our page rank in Google in addition to degrading the user experience.
Some of these broken links are for projects and companies that no longer appear to exist. In such cases when the main website is also down, I swapped in the github repo or linkedin url for the project homepage. I suggest we delete those entries from landscape.yml if they are truly dead and not coming back but I'm not sure if this is the correct practice. I can …
=> Fixes a bunch of dead urls (#3641)

landscape.yml
Adds "Upbound" to the Scheduling and Orchestration group. 
Upbound is a CNCF silver member and main contributor to the [Crossplane.io](www.crossplane.io) project, which is already in the "scheduling and orchestration" group.
* ~[ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.~
=> Adds Upbound to the Scheduling and Orchestration group

landscape.yml
- updates the repo URL for the Keptn project from the old keptn repo to the new lifecycle-toolkit
- updates the slack URL for the Keptn project since we shut down our own slack workspace in favor of the CNCF one
=> Update Keptn repo URL and Slack URL

landscape.yml
Removed Endress+Hauser crunchbase entry and added manual description
Dear CNCF Team, as contact for Endress+Hauser I would like to remove the currently used Crunchbase entry and switch to a static description. On Crunchbase only single Endress+Hauser entities are represented, not the whole group.
If we in the future are able to provide a single group-wide entry we will switch to this Crunchbase entry. For now however, we would like to remove it.
=> Removed Endress+Hauser crunchbase entry

README.md
This PR adds a new TAG section to the README file that explains how projects are classified by TAG automatically at the moment and how to set a project's TAG manually.
/cc @caniszczyk
=> Add TAGs section to README file

landscape.yml
Updating Habor's TAG label to match the requirement of the [README](https://github.com/cncf/landscape?tab=readme-ov-file#technical-advisory-groups-tag)
Once this PR merge and it work as expected, a follow-up PR would be made to update the remaining 22 instances of the `cncf_tags:` label.
After that work will be started to ensure all project have the correct TAG assigned in the "extras" field.
=> Update harbor TAG label to match README requiements

landscape.yml
Confirmed the `tag:` function work as expected in #3845 
This PR clean up all `cncf_tag` labels in the file
=> Update TAG labels to match README requirements

.github/workflows/preview.yml
This PR adds a new workflow named `preview` that automatically prepares a landscape preview link and posts it in a comment when a pull request is created.
=> Add preview workflow

landscape.yml
Add spec attribute to CE so it shows up via https://landscape.cncf.io/?specification=true
=> Add spec attribute to CE

landscape.yml
I am adding "clomonitor_name: microcks" to Microcks extra fields. 
Because it is mandatory to pass the "Summary Table" check.
=> Update landscape.yml for Microcks extra missing field

landscape.yml
Updating the projects identified in the [TAG Security README](https://github.com/cncf/tag-network?tab=readme-ov-file#current-cncf-network-centric-projects) as network centric projects.
It is in preperation for the replacement of the list of projects on the README with a filtered [TAG Network landscape link](https://landscape.cncf.io/?group=projects-and-products&view-mode=grid&tag=network&project=cncf).
=> Add TAG Network project tags to landscape.yml file

landscape.yml
The keywhiz project is archived, deprecated and no longer maintained according to their github page, so propose it is removed from the CNCF landscape https://github.com/square/keywhiz
*[ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
=> Remove keywhiz

landscape.yml
Originally I requested Kairos to be in the current category just because I saw other projects like FlatCar there, but in reality Kairos is not involved in WASM. I believe Runtime or Provisioning reflect better the goal of the project and from those I felt automation & configuration was the best fit with how the landscape is currently split. Ideally, I'd like to see a section under the Runtime called special purpose OS or something along those lines like we have in the charter [1]
[1]: https://tag-runtime.cncf.io/wgs/spos/charter/
=> Move Kairos to different category/subcategory

landscape.yml
Dedupes projects that are located in multiple categories and switches them to using `second_path`.
Moves flatcar to Platform category so that  it is accounted for on the website correctly.
=> Project Updates (second_path & relocate flatcar)

landscape.yml
Metatype is now 100% open source ([ref](https://github.com/metatypedev/metatype/pull/899)).
=> feat: add github url to metatype

landscape.yml
=> fix: project jupyter repo_url hyperlink

landscape.yml
Per the announcement at Open Source Summit Europe 2024, OpenSearch is now part of The Linux Foundation: https://www.linuxfoundation.org/press/linux-foundation-announces-opensearch-software-foundation-to-foster-open-collaboration-in-search-and-analytics
updated cunchbase URL accordingly.
Other metadata that indicates the owning organization in the landscape should also be updated accordingly (currently still indicating "Amazon Web Services")
* [ x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub …
=> Update landscape.yml - OpenSearch project now under The Linux Foundation

landscape.yml
Rename our repository from `Dragonfly2` to `dragonfly` to better align with our project naming conventions and to avoid any potential confusion. This change will help us maintain consistency across our project repositories and improve the overall clarity of our project structure.
Refer to https://github.com/dragonflyoss/dragonfly/issues/3714.
=> chore: rename repo dragonflyoss/Dragonfly2 to dragonflyoss/dragonfly

landscape.yml
As discussed with @angellk & @mrbobbytables the website is incorrect and pointing towards a Red Hat Website insteat of the official website
=> Update Operator Framework Website

landscape.yml
The Cartography project has a website now! https://cartography.dev.
Updates the link in landscape.yml.
See https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2642.
=> CNCFSD-2642: Add website for Cartography

landscape.yml
Cloudsmith is already a CNCF member account and should be added to the container registry view: https://landscape.cncf.io/?group=members&item=cncf-members--silver--cloudsmith-member
=> Add Cloudsmith to the Container Registry Landscape

README.md, code-of-conduct.md
Updated references to CNCF repositories from 'master' to 'main' branch in the following links:
- https://github.com/cncf/foundation/blob/master/code-of-conduct.md → https://github.com/cncf/foundation/blob/main/code-of-conduct.md
- https://github.com/cncf/toc/blob/master/DEFINITION.md → https://github.com/cncf/toc/blob/main/DEFINITION.md
=> Fix outdated links to CNCF repositories (master -> main)

landscape.yml
Updated the Tinkerbell GitHub repository link to the correct URL.
=> Fix Tinkerbell GitHub repository link

landscape.yml
This PR adds ModelPack under App Definition and Development → Application Definition & Image Build.
Fixes https://github.com/cncf/landscape/issues/4477
=> Add ModelPack to Application Definition & Image Build (Sandbox)
